npm install showdown -g
showdown makehtml -i "$PSScriptRoot\README.md" -o "$PSScriptRoot\README.html"
showdown makehtml -i "$PSScriptRoot\LICENSE.md" -o "$PSScriptRoot\LICENSE.html"
showdown makehtml -i "$PSScriptRoot\CONTRIBUTING.md" -o "$PSScriptRoot\CONTRIBUTING.html"
showdown makehtml -i "$PSScriptRoot\CODE_OF_CONDUCT.md" -o "$PSScriptRoot\CODE_OF_CONDUCT.html"
Remove-Item "$PSScriptRoot\README.md"
Remove-Item "$PSScriptRoot\LICENSE.md"
Remove-Item "$PSScriptRoot\CONTRIBUTING.md"
Remove-Item "$PSScriptRoot\CODE_OF_CONDUCT.md"
Remove-Item "$PSScriptRoot\*.ps1"